<a href="https://colab.research.google.com/github/chenyufei-lianxi/pytorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [3]:
my_list=[[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [10]:
np1=np.random.rand(3,4)
np1

array([[0.78734276, 0.22281132, 0.33213887, 0.51768101],
       [0.34743851, 0.8180202 , 0.0980492 , 0.743844  ],
       [0.85075741, 0.10074373, 0.89790255, 0.09747306]])

In [5]:
np1.dtype

dtype('float64')

In [12]:
tensor_2d=torch.randn(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [8]:
tensor_3d=torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
##create tensor out of numpy array
my_tensor=torch.tensor(np1)
my_tensor

tensor([[0.7873, 0.2228, 0.3321, 0.5177],
        [0.3474, 0.8180, 0.0980, 0.7438],
        [0.8508, 0.1007, 0.8979, 0.0975]], dtype=torch.float64)